name: solar system workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'Feature/*'
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
jobs:
    code-coverage:
        name: code coverage
        
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: setup node js versio 18
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: install depend.
              run: npm install
              
            - name: check code coverage 
              run:  npm run coverage 
            - name: arch result 
              uses : actions/upload-artifact@v3 
              with :
                name: code_coverage_resultee 
                path: coverage
                retention-days: 5
                


